### ISSUE TITLE
Inconsistent sort order with gulp-inject

### ISSUE THREAD

**Issue by peluja1012** [klei/gulp-angular-filesort#17]
The order of the script tags injected into my html file is not consistent across runs, even when the files in my directory haven't changed. My code looks like this:

```javascript
gulp.src(paths.template)
  .pipe(inject(
    gulp.src(['ng/js/app/**/*.js']).pipe(angularFilesort())
  ))
  .pipe(gulp.dest(paths.templateDir));
```

**Comment by hindsholm** [comment]
I am having the same problem and would love to see the fix by max-mathieu accepted!

**Comment by ejdyksen** [comment]
Globs in gulp don't guarantee any order, so this problem comes up frequently in places where order matters in gulp.

If you sort the files first in the stream using [gulp-natural-sort](https://github.com/emgeee/gulp-natural-sort), gulp-angular-filesort will start doing the same thing every time.

Excerpt:
```js
  gulp.src('app/**/*.js')
    .pipe(naturalSort())
    .pipe(angularFilesort())
    .pipe(concat('main.js'))
    .pipe(gulp.dest('build'))
```

**Comment by kozmic** [comment]
+1 for merging max-mathieu's fix

**Comment by max-mathieu** [comment]
Sorry for the premature title of the commit

My fix is actually not working with larger codebases, and I could not look into it further, so I withdrew the pull request back in December. This was working great on smaller subsets, and I don't have lots of time to work on a better fix right now

ejdyksen's suggestion https://github.com/klei/gulp-angular-filesort/issues/17#issuecomment-69228964 is a very easy fix and works as designed for me

**Comment by swashcap** [comment]
:+1: Definitely seeing this issue.

**Comment by mmmeff** [comment]
Any chance of this getting merged in any time soon?

**Comment by joakimbeng** [comment]
This is not a task for gulp-inject. Use the solution provided by @ejdyksen above.

**Comment by mmmeff** [comment]
Ah, my apologies for misunderstanding. Thanks for pointing it out.
[[selfie-placeholder-0]]

**Comment by joakimbeng** [comment]
No worries :)
