### ISSUE TITLE
Parsing index.html breaks on doctype

### ISSUE THREAD

**Issue by DeezCashews** [klei/gulp-angular-filesort#33]
Error: Error in parsing: "index.html", Line 1: Unexpected token <

Line 1:  `<!DOCTYPE html>`

**Comment by joakimbeng** [comment]
You shouldn't pass html files to this plugin... It only deals with JavaScript.

**Comment by DeezCashews** [comment]
Not sure why it gave my this except that maybe my cached templates in
template.min.js had html like syntax in them.

--
Andrew C Wynham
Principal Consultant
TILT Development, Inc.
703.864.0247

**Comment by umacys** [comment]
I believe, having html statements in a directive is common. So, at the end, it may not be the html the user is parsing.
