### ISSUE TITLE
[Question] ag-grid

### ISSUE THREAD

**Issue by shinrox** [klei/gulp-angular-filesort#35]
Hi,

I'm not sure if this is the right repo to place this issue, but I'm using the [ag-grid](https://github.com/ceolter/ag-grid) package the ag-grid is not being injected correctly after angular.js, it only works if I install like `bower install angular-grid=ag-grid`

I'm not sure, but I think it's because the folder sctructure, and due to the optional usage of angular in that project

I've opened an [issue](https://github.com/ceolter/ag-grid/issues/446) in their repo as well

**Comment by johnwebbcole** [comment]
If you're using bower-main-files to feed gulp-angular-filesort, you can add an override to your bower file to add an angular dependency to ag-grid:

```json
"overrides": {
   "ag-grid": {
      "dependencies": {
        "angular": "*"
      }
    }
  }
```

This will allow angular-filesort to order ag-grid after angular.  See main-bower-files [override-options](https://github.com/ck86/main-bower-files#overrides-options) for more info.

**Comment by shinrox** [comment]
Nice, it worked. Thanks =)
