### ISSUE TITLE
ES6 Class breaks build as "reserved keyword"

### ISSUE THREAD

**Issue by daanaerts** [klei/gulp-angular-filesort#37]
```
class WebSocket {
```

```
[12:01:50] [AngularFilesort] Error in plugin 'gulp-angular-filesort'
Message:
    Error in parsing: "components/api/websocket.service.js", Line 6: Unexpected reserved word
```

**Comment by PLEEROCK** [comment]
arrow functions are not working as well

**Comment by Javarome** [comment]
The sort is assuming files are ES5, so you have to transpile your ES6 to ES5 first, then sort the resulting ES5 files, like below:

```
gulp.task('es6toes5', function () {
  return gulp.src(es6Sources)
    .pipe(es6())
    .pipe(gulp.dest('es5'));
});

gulp.task('dist', ['es6toes5'], function () {
  return gulp.src('index.html')
    .pipe(inject(gulp.src(['es5/**/*.js']).pipe(angularFilesort())))
    .pipe(gulp.dest('dist'));
});
```

**Comment by daanaerts** [comment]
Thanks Javarome,

it works fine so far. Piping directly is easiest option I found.

var injectScripts = gulp.src([
      path.join(conf.paths.src, '/app/**/*.module.js'),
      path.join(conf.paths.src, '/app/**/*.js'),
      path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
      path.join('!' + conf.paths.src, '/app/**/*.mock.js')
    ])
    .pipe($.es6Transpiler({
      globals: {
        globalvars.
      }
    }))
    .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));

**Comment by Javarome** [comment]
Yes, that's far better. Thanks for the tip.

**Comment by joakimbeng** [comment]
For anyone seeing this I recommend using one of @Javarome or @daanaerts solutions above.

Or even better, skip this plugin altogether by using Browserify or Webpack...

**Comment by hustshawn** [comment]
@daanaerts May I know how your globalvars defined?

**Comment by kyleThayerXpanxion** [comment]
If you are using babel, you can just use:

```
var injectScripts = gulp.src([
      path.join(conf.paths.src, '/app/**/*.module.js'),
      path.join(conf.paths.src, '/app/**/*.js'),
      path.join('!' + conf.paths.src, '/app/**/*.spec.js'),
      path.join('!' + conf.paths.src, '/app/**/*.mock.js')
    ])
   .pipe(babel())
    .pipe($.angularFilesort()).on('error', conf.errorHandler('AngularFilesort'));
```
