### ISSUE TITLE
sort in reverse order

### ISSUE THREAD

**Issue by loganfreeman** [klei/gulp-angular-filesort#38]
exports.task = function() {
    return gulp.src('gulp/index.html')
        .pipe($.inject(
            gulp.src([
                'app.js',
                path.join(conf.paths.src, '/**/*.js'),
                path.join('!' + conf.paths.src, '/**/*spec.js'),
            ])
                .pipe($.angularFilesort())
        ))
        .pipe(gulp.dest('tmp'));

};

It gave the script tags in reverse order.

**Comment by joakimbeng** [comment]
See #44 and #45
