### ISSUE TITLE
Dependency on gulp-utils breaks gulp 4.0 alpha 3

### ISSUE THREAD

**Issue by damoncasale** [klei/gulp-angular-filesort#55]
The dependency of gulp-angular-filesort on gulp-utils totally breaks gulp 4.0 alpha 3, because gulp-utils itself has a dependency on a massively outdated version of vinyl-fs.  PLEASE FIX ASAP!!

**Comment by demurgos** [comment]
See https://github.com/gulpjs/gulp-util/issues/143
